### ISSUE TITLE
Feature request: add an option to ignore unused imports

### ISSUE THREAD

**Issue by Augustin82** [sirbrillig/phpcs-import-detection#13]
While waiting to find the time to work on #7 (I'm trying, I promise!), would it be possible to allow ignoring unused imports, similar to ignoring unimported symbols via the configuration option?

**Comment by sirbrillig** [comment]
You should be able to do that now actually, by disabling `ImportDetection.Imports.RequireImports.Import`. Try a phpcs.xml config like this:

```xml
<?xml version="1.0"?>
<ruleset name="MyStandard">
 <description>My library.</description>
 <rule ref="ImportDetection"/>
 <rule ref="ImportDetection.Imports.RequireImports.Import">
   <severity>0</severity>
 </rule>
</ruleset>
```

... I should put information like that in the README.

**Comment by Augustin82** [comment]
My mistake, I wasn't clear at all, sorry =(

What I meant is the ability to ignore some of them, using a regex, like it works with `ignoreUnimportedSymbols`.

**Comment by sirbrillig** [comment]
😅 oh! sorry I misunderstood! I think you can use the patterns in `ignoreUnimportedSymbols` for this already. I realize the name is misleading, though. 🤔 It should probably just be `ignoreSymbolPatterns` (it should also accept an array rather than just a single string... this is a future improvement I'm working on).

**Comment by Augustin82** [comment]
Wow, thank you so much for being so reactive, it's impressive =)

I have just tested it out, and it seems that I can successfully ignore "simple" patterns (such as ignoring `use unused_function;` with the pattern `/^(unused_function)$/`) but it doesn't work for `use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;` using the pattern `/^(Route)$/` or even `/^(.*oute)$/` =(

**Comment by sirbrillig** [comment]
Oh, you're right! There's a bug in how imported symbols are treated.

**Comment by sirbrillig** [comment]
So that should work now, however, the ignore pattern must be able to match the entire imported symbol if you want it to ignore the unused import.

For example if the code has this unused symbol (`Route` is not used anywhere else in the file):

```php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
```

Then the ignore pattern `/^Route$/` will fail and an unused import will be reported as a warning, but the pattern `/Route$/` should match and the import will be ignored.

**Comment by Augustin82** [comment]
Wow, it's great, and the pattern on the full import is quite nice, that's how I viewed it =)
