### ISSUE TITLE
array keys must be in string forms

### ISSUE THREAD

**Issue by zanona** [sirbrillig/phpcs-import-detection#28]
Hi,
I have spotted that array keys must be in the string form after trying to validate the following code:

```php
array(
    type    => 'option',
    'default' => 'Sample Company Address',
)
```

I get `Found unimported symbol 'type'`.
Just checking if this is a limitation or something that could perhaps be added to this plugin?

I'm new to PHP and perhaps that's bad practice to not using keys in string forms at all?
Thanks in advance

**Comment by sirbrillig** [comment]
To my knowledge, array keys in PHP must always be explicit. 

In JavaScript, we can define object properties without surrounding the property key with strings. This is actually just a happy side-effect of the fact that JS objects are not really designed to be used as dictionaries for data (there's the `Map` type for that now). In fact, in JSON, the JS schema for data, keys must be quoted.

In PHP, a bare word string like `type` will be interpreted as a function, constant, or class reference. PHP is totally fine with using non-strings as associative array keys (for example, an indexed array uses numbers as the keys), but using a class called `type` is very likely not what you mean here. If you want the key to be a string, it must be a string type (and therefore must be quoted).

If the above code actually works, you should check your PHP warning log, because sometimes PHP will automatically convert undefined bare words into strings for you with a warning, but it's very risky to rely on that behavior (and it [could be removed](https://wiki.php.net/rfc/deprecate-bareword-strings) in a future version of the language).

**Comment by zanona** [comment]
Thanks so much for the thorough explanation.
