### ISSUE TITLE
False positive on `Found unimported symbol` v1.2.1

### ISSUE THREAD

**Issue by zanona** [sirbrillig/phpcs-import-detection#32]
Hello,
I just upgraded to `v1.2.1` and started to get warnings on the below: 

```php
function foo() {}
add_action( 'init', foo );
```
> Found unimported symbol 'foo'. (ImportDetection.Imports.RequireImports.Symbol)

logs:
```sh
>> composer upgrade
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 4 updates, 0 removals
  - Updating squizlabs/php_codesniffer (3.5.2 => 3.5.3): Downloading (100%)         
  - Updating wp-coding-standards/wpcs (2.1.1 => 2.2.0): Downloading (100%)         
  - Updating sirbrillig/phpcs-variable-analysis (v2.7.0 => v2.8.0): Downloading (100%)         
  - Updating sirbrillig/phpcs-import-detection (v1.1.4 => v1.2.1): Downloading (100%)         
```
It's strange because it was definitely not the case on 1.1.4

Thanks

**Comment by sirbrillig** [comment]
Oh, that must be a bug introduced in 1.2. Thanks for finding it!

**Comment by sirbrillig** [comment]
Hm... actually I think that might be expected behavior, since there's no defined symbol `foo` (you can't pass functions by reference in PHP, only as strings or inside variables).

So your example would need to be written as

```php
function foo() {}
add_action( 'init', 'foo' );
```

This may be confusing because if PHP encounters an undefined symbol (like `foo` in your above example), it will issue a warning and try converting it to a string. Because of this fallback, your example may seem like valid PHP, but it's not doing what you might think it's doing; it's actually still using a string. In a future version of php, this fallback may be removed, so it's recommended to avoid it (see the warning [here](https://www.php.net/manual/en/migration72.deprecated.php)).

> Unquoted strings that are non-existent global constants are taken to be strings of themselves. This behaviour used to emit an E_NOTICE, but will now emit an E_WARNING. In the next major version of PHP, an Error exception will be thrown instead.

**Comment by sirbrillig** [comment]
See also the [docs on passing functions as arguments](https://www.php.net/manual/en/language.types.callable.php).

**Comment by zanona** [comment]
@sirbrillig thanks for taking a look on this. However, this behaviour seemed to have changed from 1.1.4 to 1.2? I will change my codebase accordingly here, so I can be on the latest version.

**Comment by sirbrillig** [comment]
Yeah, confirmed that it doesn't mark it as a warning in 1.1.4. This must have been a bug that I never saw. I just added a test in #33 to make sure we don't cause a regression in the future!

**Comment by zanona** [comment]
Just getting back to this now:
```php
function import( $path ) {
	require_once get_stylesheet_directory() . '/' . $path . '.php';
}

import( 'lib/features' ); //<<<Found unimported symbol 'import'. (ImportDetection.Imports.RequireImports.Symbol)
```
it doesn't seem to be applied only to callbacks as initially thought?

**Comment by sirbrillig** [comment]
Ooo. That's what I first thought was going on. Thank you for following up. 🙇
