### ISSUE TITLE
Do not warn on relative imports

### ISSUE THREAD

**Issue by szepeviktor** [sirbrillig/phpcs-import-detection#45]
I've just realized `ImportDetection` warns when I use a relative class

```php
namespace SpaceForce;

//use SpaceForce\Config; 👈 it is necessary

class Caller
{
    static function init()
    {
        Config::init();
    }
}
```

It would be nice to have :)

```xml
    <property name="ignoreRelativeScope" value="true"/>
```

**Comment by sirbrillig** [comment]
If I understand correctly (please correct me if I'm wrong), you mean that `Config::init();` gives a warning unless you include `use SpaceForce\Config;` even though it's in the same namespace?

If so, this was also discussed in https://github.com/sirbrillig/phpcs-import-detection/issues/8 and https://github.com/sirbrillig/phpcs-import-detection/issues/37. The problem is that there's no easy way for the sniff to _know_ that `Config` is in the namespace since it is only looking at this one file. Basically this sniff is a poor substitute for static analysis checkers like `psalm` or `phpstan` which may be able to draw those conclusions.

**Comment by szepeviktor** [comment]
Thank you for your answer.

> since it is only looking at this one file

Could ImportDetection take a look at the `namespace` statement at the top of the file?

**Comment by sirbrillig** [comment]
I believe that it does. The following code should not create warnings:

```php
namespace SpaceForce;

class Caller
{
    static function init()
    {
        SpaceForce\Config::init(); // notice there is no leading backslash
    }
}
```

**Comment by szepeviktor** [comment]
Okay-okay.

Just saying `namespace SpaceForce;` then `SpaceForce...` again will not meet people's liking...

**Comment by szepeviktor** [comment]
Could ImportDetection remember the file's namespace?

**Comment by sirbrillig** [comment]
(I had to revise this reply because I think I got confused the first time; sorry!)

> Could ImportDetection take a look at the namespace statement at the top of the file?

Could you elaborate on this? How would you imagine it working?

**Comment by szepeviktor** [comment]
Oh! I see :) ImportDetection will not know that `Config` is in the same namespace...

**Comment by sirbrillig** [comment]
Yeah, sorry! I'd like it to work too but I can't figure out how to do it without making this way more complex and opening other files.

**Comment by szepeviktor** [comment]
I think a [PHPStan extension](https://phpstan.org/developing-extensions/extension-types) could be written in ~50 lines.
