### ISSUE TITLE
false positive unused imports

### ISSUE THREAD

**Issue by mirzazeyrek** [sirbrillig/phpcs-import-detection#54]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/6233650/157454409-b56218e2-93c9-4966-a8e2-7d32a665ce0a.png">

Is there a way to get rid of this type of warnings ? Even though the namespace is specified it gives a warning about Unused imports.

**Comment by sirbrillig** [comment]
Thank you for the report!

I'm confused about exactly what's happening in the example you gave.

> namespace XXXXXX\GameEvent;

The above statement says, "The following code is inside the `GameEvent` namespace."

> class XXX extends GameEvent

Then this statement says, "This class should extend a _class_ named `GameEvent`.", and that shows a warning because you haven't defined or imported any classes called `GameEvent`. 

Assuming that you have a class called `\GameEvent\GameEvent` (a class `GameEvent` in the namespace `GameEvent`) in some other file, then this makes a lot more sense, but this sniff will still display it as a warning because in order to know that class exists, the linter would have to look inside your other files. There's not even a `require` statement at the top of this file so even if we wanted to look inside the other files, we wouldn't know where to look. Does that make sense?

This sniff is a simple tool for making sure you don't use unimported symbols. If you'd like to have a tool that will make sure your classes and variables are correct, you should use a static analysis system like [phpstan](https://phpstan.org/) or [psalm](https://psalm.dev/). They might do exactly what you're looking for.

**Comment by mirzazeyrek** [comment]
thanks for the insightful explanation!
