### ISSUE TITLE
Publish the fix for the deprecation notice

### ISSUE THREAD

**Issue by jestillore** [sirbrillig/phpcs-import-detection#57]
Can you publish this [commit](https://github.com/sirbrillig/phpcs-import-detection/commit/7035ef6f3a15db182b59664d2c060918aa827e16) already?
The current latest version is still `v1.3.2` that doesn't include this fix.

**Comment by sirbrillig** [comment]
I've published https://github.com/sirbrillig/phpcs-import-detection/releases/tag/v1.3.3. Note that because of https://github.com/sirbrillig/phpcs-import-detection/issues/52 this sniff probably won't work in phpcs 3.5.1, but you can try it. I unfortunately haven't had the cycles to fix the bugs in this sniff yet.
